version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: newsletterai
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: newsletterai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: